#![allow(dead_code)]

use winapi::shared::minwindef::*;
use winapi::um::winuser::*;

//winsdk 7.0A  windowx.h
//pub const WM_CTLCOLOR:			UINT = 0x0019;

//winsdk 7.0A  OleCtl.h
pub const OCM__BASE: 			UINT = WM_USER + 0x1c00;
pub const OCM_COMMAND: 			UINT = OCM__BASE + WM_COMMAND;

pub const OCM_CTLCOLORBTN: 		UINT = OCM__BASE + WM_CTLCOLORBTN;
pub const OCM_CTLCOLOREDIT: 	UINT = OCM__BASE + WM_CTLCOLOREDIT;
pub const OCM_CTLCOLORDLG: 		UINT = OCM__BASE + WM_CTLCOLORDLG;
pub const OCM_CTLCOLORLISTBOX: 	UINT = OCM__BASE + WM_CTLCOLORLISTBOX;
pub const OCM_CTLCOLORMSGBOX: 	UINT = OCM__BASE + WM_CTLCOLORMSGBOX;
pub const OCM_CTLCOLORSCROLLBAR:UINT = OCM__BASE + WM_CTLCOLORSCROLLBAR;
pub const OCM_CTLCOLORSTATIC: 	UINT = OCM__BASE + WM_CTLCOLORSTATIC;
//pub const OCM_CTLCOLOR: 		UINT = OCM__BASE + WM_CTLCOLOR;

pub const OCM_DRAWITEM: 		UINT = OCM__BASE + WM_DRAWITEM;
pub const OCM_MEASUREITEM: 		UINT = OCM__BASE + WM_MEASUREITEM;
pub const OCM_DELETEITEM: 		UINT = OCM__BASE + WM_DELETEITEM;
pub const OCM_VKEYTOITEM: 		UINT = OCM__BASE + WM_VKEYTOITEM;
pub const OCM_CHARTOITEM: 		UINT = OCM__BASE + WM_CHARTOITEM;
pub const OCM_COMPAREITEM: 		UINT = OCM__BASE + WM_COMPAREITEM;
pub const OCM_HSCROLL: 			UINT = OCM__BASE + WM_HSCROLL;
pub const OCM_VSCROLL: 			UINT = OCM__BASE + WM_VSCROLL;
pub const OCM_PARENTNOTIFY: 	UINT = OCM__BASE + WM_PARENTNOTIFY;

pub const OCM_NOTIFY: 			UINT = OCM__BASE + WM_NOTIFY;



pub const WINSTATE_DESTROYED: DWORD = 0x00000001;

pub const DWLP_MSGRESULT: LRESULT = 0;
